// Generated by scripts/release-config.py --write. Edit config/Release.json.
public enum TokenotchProduct {
    public static let name = "Tokenotch"
    public static let version = "1.0.0"
    public static let build = "1"
    public static let minimumOS = "15.0"
    public static let bundleID = "io.github.rottathiago.tokenotch"
    public static let repository = "rottathiago/tokenotch"
    public static let publisher = "rottathiago"
    public static let companionName = "tokenotch-vscode"
    public static let storageDirectory = ".tokenotch"
    public static let companionID = publisher + "." + companionName
}
