#!/usr/bin/env python3
"""Generate and verify the small cross-language release identity contract."""
import argparse
import json
import pathlib
import plistlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent


def windows_configuration():
    config = json.loads((ROOT / "windows/config/release.json").read_text())
    if (set(config) != {"minimumWindowsBuild", "architectures", "installer", "installMode", "dataDirectory", "channel"}
            or type(config["minimumWindowsBuild"]) is not int or config["minimumWindowsBuild"] < 22000
            or config["architectures"] != ["x64", "arm64"] or config["installer"] != "nsis"
            or config["installMode"] != "currentUser" or config["dataDirectory"] != "Tokenotch"
            or config["channel"] != "development"):
        raise ValueError("Invalid Windows development configuration")
    return config


def configuration():
    config = json.loads((ROOT / "config/Release.json").read_text())
    patterns = {
        "name": r"Tokenotch",
        "version": r"(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)",
        "build": r"[1-9][0-9]*",
        "minimumOS": r"[0-9]+\.[0-9]+",
        "bundleID": r"[a-zA-Z][a-zA-Z0-9-]*(\.[a-zA-Z0-9-]+){2,}",
        "repository": r"[A-Za-z0-9-]+/[A-Za-z0-9_.-]+",
        "publisher": r"[A-Za-z0-9][A-Za-z0-9-]*",
        "companionName": r"tokenotch-vscode",
        "storageDirectory": r"\.tokenotch",
    }
    if set(config) != set(patterns):
        raise ValueError("Release configuration has missing or unknown fields")
    for key, pattern in patterns.items():
        if not isinstance(config[key], str) or not re.fullmatch(pattern, config[key]):
            raise ValueError(f"Invalid release field: {key}")
    if (config["repository"] != f"{config['publisher']}/tokenotch"
            or config["bundleID"] != f"io.github.{config['publisher']}.tokenotch"):
        raise ValueError("Repository, bundle identifier, and publisher must share the owned Tokenotch identity")
    return config


def generated(config):
    swift = "// Generated by scripts/release-config.py --write. Edit config/Release.json.\n"
    swift += "public enum TokenotchProduct {\n"
    for key, value in config.items():
        swift += f"    public static let {key} = {json.dumps(value)}\n"
    swift += '    public static let companionID = publisher + "." + companionName\n}\n'
    xcconfig = "// Generated by scripts/release-config.py --write.\n"
    for key, value in {
        "PRODUCT_BUNDLE_IDENTIFIER": config["bundleID"],
        "MARKETING_VERSION": config["version"],
        "CURRENT_PROJECT_VERSION": config["build"],
        "MACOSX_DEPLOYMENT_TARGET": config["minimumOS"],
        "INFOPLIST_KEY_CFBundleDisplayName": config["name"],
        "INFOPLIST_KEY_CFBundleIconFile": "Tokenotch",
        "ARCHS": "arm64 x86_64",
        "ONLY_ACTIVE_ARCH": "NO",
    }.items():
        xcconfig += f"{key} = {value}\n"
    windows = windows_configuration()
    desktop = json.loads((ROOT / "windows/config/desktop.json").read_text())
    desktop.update(productName=config["name"], version=config["version"], identifier=config["bundleID"])
    product = {
        "name": config["name"], "version": config["version"], "build": config["build"],
        "repository": config["repository"], **windows,
    }
    rust = "// Generated by scripts/release-config.py --write. Do not edit.\n"
    for name, value in {"NAME": config["name"], "VERSION": config["version"],
                        "BUILD": config["build"], "REPOSITORY": config["repository"],
                        "DATA_DIRECTORY": windows["dataDirectory"], "CHANNEL": windows["channel"]}.items():
        rust += f"pub const {name}: &str = {json.dumps(value)};\n"
    rust += f"pub const MINIMUM_WINDOWS_BUILD: u32 = {windows['minimumWindowsBuild']};\n"
    return {
        ROOT / "sources/Core/TokenotchProduct.swift": swift,
        ROOT / "config/Release.xcconfig": xcconfig,
        ROOT / "integrations/VSCode/src/product.cjs":
            "'use strict';\n// Generated by scripts/release-config.py --write.\n"
            + "module.exports = Object.freeze(" + json.dumps(config, indent=2) + ");\n",
        ROOT / "windows/core/src/product.rs": rust,
        ROOT / "windows/desktop/src/product.js":
            "// Generated by scripts/release-config.py --write. Do not edit.\n"
            + "export const product = Object.freeze(" + json.dumps(product, indent=2) + ");\n",
        ROOT / "windows/desktop/src-tauri/tauri.conf.json": json.dumps(desktop, indent=2) + "\n",
        ROOT / "windows/config/minimum-build.nsh":
            "; Generated by scripts/release-config.py --write. Do not edit.\n"
            + f"!define TOKENOTCH_MINIMUM_WINDOWS_BUILD {windows['minimumWindowsBuild']}\n",
    }


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--write", action="store_true")
    parser.add_argument("--plist", type=pathlib.Path)
    parser.add_argument("--distribution", choices=["development", "release"], default="development")
    parser.add_argument("--field")
    args = parser.parse_args()
    config = configuration()
    if args.field:
        print(config[args.field])
        return
    if args.plist:
        info = {
            "CFBundleIdentifier": config["bundleID"],
            "CFBundleName": config["name"],
            "CFBundleDisplayName": config["name"],
            "CFBundleExecutable": config["name"],
            "CFBundleIconFile": "Tokenotch",
            "CFBundlePackageType": "APPL",
            "CFBundleShortVersionString": config["version"],
            "CFBundleVersion": config["build"],
            "LSMinimumSystemVersion": config["minimumOS"],
            "LSUIElement": True,
            "TokenotchDistributionChannel": args.distribution,
            "NSHumanReadableCopyright": "Copyright (c) 2026 rottathiago. Includes MIT-licensed code, Copyright (c) 2026 Vinz.",
        }
        args.plist.write_bytes(plistlib.dumps(info))
        return
    failures = []
    for path, content in generated(config).items():
        if args.write:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content)
        elif not path.exists() or path.read_text() != content:
            failures.append(str(path.relative_to(ROOT)))
    package_path = ROOT / "integrations/VSCode/package.json"
    package = json.loads(package_path.read_text())
    expected = {
        "name": config["companionName"],
        "version": config["version"],
        "publisher": config["publisher"],
        "license": "MIT",
        "repository": {
            "type": "git",
            "url": f"https://github.com/{config['repository']}.git",
            "directory": "integrations/VSCode",
        },
    }
    lock_path = ROOT / "integrations/VSCode/package-lock.json"
    lock = json.loads(lock_path.read_text())
    expected_lock = {"name": config["companionName"], "version": config["version"]}
    expected_lock_root = {**expected_lock, "license": "MIT"}
    if args.write:
        package.update(expected)
        package_path.write_text(json.dumps(package, indent=2) + "\n")
        lock.update(expected_lock)
        lock["packages"][""].update(expected_lock_root)
        lock_path.write_text(json.dumps(lock, indent=2) + "\n")
    else:
        if any(package.get(key) != value for key, value in expected.items()):
            failures.append("integrations/VSCode/package.json")
        if (any(lock.get(key) != value for key, value in expected_lock.items())
                or any(lock["packages"][""].get(key) != value for key, value in expected_lock_root.items())):
            failures.append("integrations/VSCode/package-lock.json")
    for relative in ["integrations/VSCode/LICENSE"]:
        path = ROOT / relative
        license_text = (ROOT / "LICENSE").read_text()
        if args.write:
            path.write_text(license_text)
        elif not path.exists() or path.read_text() != license_text:
            failures.append(relative)
    if failures:
        raise ValueError("Release metadata is stale: " + ", ".join(failures) +
                         ". Run python3 scripts/release-config.py --write.")
    print("Release metadata is consistent.")


if __name__ == "__main__":
    try:
        main()
    except (ValueError, KeyError, OSError) as error:
        print(f"Release configuration error: {error}", file=sys.stderr)
        sys.exit(1)
