// Generated by scripts/release-config.py --write. Do not edit.
export const product = Object.freeze({
  "name": "Tokenotch",
  "version": "1.0.0",
  "build": "1",
  "repository": "rottathiago/tokenotch",
  "minimumWindowsBuild": 26100,
  "architectures": [
    "x64",
    "arm64"
  ],
  "installer": "nsis",
  "installMode": "currentUser",
  "dataDirectory": "Tokenotch",
  "channel": "development"
});
